// <auto-generated />
namespace TreeViewDemo.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class initializeImageCol : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initializeImageCol));
        
        string IMigrationMetadata.Id
        {
            get { return "201501210550171_initializeImageCol"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
